name: fit_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  url_launcher: ^6.2.5
  just_audio: ^0.9.36
  fl_chart: ^0.66.0
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
    
flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png
    - assets/login_bg.jpg
    - assets/logo.jpg
    - assets/start.jpg

  # If you plan to use custom assets or fonts later, uncomment and add them here:
  # assets:
  #   - assets/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
